modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = "A valid URL to your issue tracker where people can open bug tickets"
license = "MIT License"

[[mods]]
modId = "redscobblemonutilities"
version = "${version}"
displayName = "Red's Cobblemon Utilities"
authors = "JustRed23"
description = '''
Some much needed improvements to the Cobblemon experience.
'''
#logoFile = ""

[[dependencies.redscobblemonutilities]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.redscobblemonutilities]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.66,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.redscobblemonutilities]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6,)"
ordering = "AFTER"
side = "BOTH"
